import type { Metadata } from 'next'
import Providers from './providers'
import { Toaster } from 'sonner'

export const metadata: Metadata = {
  title: 'Hono | nextjs',
  description: 'Generated by hono',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang='en'>
      <body>
        <Providers>{children}</Providers>
        <Toaster richColors position='top-center' closeButton />
      </body>
    </html>
  )
}
